version: '3.7'

services:
  db:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data:rw
  db-test:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
    ports:
      - "${DB_TEST_PORT}:5432"
    volumes:
      - db-test:/var/lib/postgresql/data:rw

volumes:
  db: ~
  db-test: ~
