version: '3.7'

services:
  db:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data:rw

volumes:
  database: ~
